const cartActionTypes = {
  ADD_ITEM_TO_CART_START: "ADD_ITEM_TO_CART_START",
  ADD_ITEM_TO_CART_SUCCESS: "ADD_ITEM_TO_CART_SUCCESS",
  ADD_ITEM_TO_CART_FAILURE: "ADD_ITEM_TO_CART_FAILURE",
  TOGGLE_HIDDEN_AND_SHOW: "TOGGLE_HIDDEN_AND_SHOW",
  DECREAS_ITEM: "DECREAS_ITEM",
  CLEAR_ITEM_FROM_CARTITEM: "CLEAR_ITEM_FROM_CARTITEM",
};

export default cartActionTypes;
