const userActionType = {
  START_SET_CURRENT_USER_SING_IN: "START_SET_CURRENT_USER_SING_IN",
  START_SET_CURRENT_USER_SING_UP: "START_SET_CURRENT_USER_SING_UP",
  SUCCESS_SET_CURRENT_USER: "SUCCESS_SET_CURRENT_USER",
  FAILURE_SET_CURRENT_USER: "FAILURE_SET_CURRENT_USER",
};
export default userActionType;
